fix(shipments): fix carrier defaulting on update action
myparcelnl/pdk pull request #108
Opened 2023-06-20 11:28 UTC by Mark-Ernst

2023-06-20 11:29 UTC, Mark-Ernst commented
Ik weet dat de tests nog falen bij deze. Van 1 test moet de snapshot worden geupdate, maar het falen van de andere test is volgens mij geen gevolg van mijn branch. Het instantieren van een carrier met id 4 geeft blijkbaar een carrier terug met de waarde null als name

2023-06-20 12:54 UTC, joerivanveen approved these changes

2023-06-21 07:26 UTC, EdieLemoine requested changes

2023-06-21 07:26 UTC, EdieLemoine commented on src/Shipment/Response/GetShipmentsResponse.php
> +                    'externalIdentifier' => $carrier->name,
dit moet niet name zijn, en hoef je niet in te vullen, gaat vanzelf op basis van carrier name en contract id

2023-06-21 07:26 UTC, EdieLemoine commented on src/Shipment/Response/GetShipmentsResponse.php
> +                    'name'               => $carrier->name,
name hoef je niet in te vullen, gaat vanzelf op basis van carrier id

2023-06-21 12:48 UTC, EdieLemoine approved these changes

2023-06-21 12:52 UTC, merged