feat(fulfilment): add order notes
myparcelnl/pdk pull request #122
Opened 2023-07-13 11:30 UTC by Mark-Ernst

2023-07-13 14:17 UTC, EdieLemoine requested changes
laten we morgen even samen erdoorheen lopen

2023-07-13 14:17 UTC, EdieLemoine commented on src/App/Action/Backend/Order/ExportOrderAction.php
> +        $apiOrders->each(function (Order $order) {
Dit moet in een losse action gebeuren, zo kan je deze handeling nu ook niet los aanroepen vanuit bijvoorbeeld een hook in WooCommerce

2023-07-13 14:17 UTC, EdieLemoine commented on src/App/Order/Contract/PdkOrderRepositoryInterface.php
> +     * @param $orderIds
waarom is dit veranderd? nu is de informatie van de param weg

2023-07-13 14:17 UTC, EdieLemoine commented on src/Fulfilment/Repository/OrderNotesRepository.php
> +            return null;
Dit moet altijd null returnen totdat we die subscription functionaliteit erin hebben. dit kan en mag niet gebruikt worden voor die tijd.

2023-07-14 09:16 UTC, Mark-Ernst commented on tests/Unit/Fulfilment/Repository/PostOrderNotesTest.php
> +    $pdk = PdkFactory::create(MockPdkConfig::create());
usesShared

2023-07-14 09:16 UTC, Mark-Ernst commented on tests/Unit/Plugin/Action/Order/ExportOrderActionTest.php
> +        ->append(new ExamplePostOrdersResponse(), new ExamplePostOrderNotesResponse());
test toevoegen

2023-07-17 19:32 UTC, Mark-Ernst commented on tests/Unit/Plugin/Action/Order/ExportOrderActionTest.php
> +        ->append(new ExamplePostOrdersResponse(), new ExamplePostOrderNotesResponse());
Ik kan in deze test dit niet echt testen, dit is een response die nodig is voor de post order notes actie die binnen in de export order actie gebeurt. Er is wel een losse test voor de post order notes actie op zichzelf.

2023-07-18 09:45 UTC, EdieLemoine requested changes

2023-07-18 09:45 UTC, EdieLemoine approved these changes

2023-07-18 10:47 UTC, joerivanveen approved these changes

2023-07-18 11:10 UTC, merged