feat(fulfilment): save order note uuids from api
myparcelnl/pdk pull request #130
Opened 2023-07-20 10:59 UTC by Mark-Ernst

2023-07-20 12:30 UTC, EdieLemoine requested changes

2023-07-20 12:30 UTC, EdieLemoine commented on src/App/Action/Backend/Order/PostOrderNotesAction.php
> +                $order->notes->each(function (PdkOrderNote $note) use ($notes) {
Dit liever in een method op de PdkOrderNoteCollection, net als `addIds` en dergelijke dingen bij shipments en orders. Kijk dan ook hoe die zijn geïmplementeerd, want dat kan wat strakker :)

2023-07-20 12:32 UTC, EdieLemoine commented on src/App/Action/Backend/Order/PostOrderNotesAction.php
> +                $order->notes->each(function (PdkOrderNote $note) use ($notes) {
plus, hoe "save" je dit nu? dit wordt nu niet opgeslagen in het platform (zie `PdkOrder::toStorableArray()`)

2023-07-20 14:00 UTC, EdieLemoine requested changes

2023-07-20 14:00 UTC, EdieLemoine commented on src/App/Action/Backend/Order/PostOrderNotesAction.php
> +                    $order->notes->filter(function (PdkOrderNote $note) {
`notes->where('apiIdentifier', '==', null)` zou hetzelfde moeten doen

2023-07-21 07:40 UTC, joerivanveen approved these changes

2023-07-21 07:58 UTC, EdieLemoine approved these changes

2023-07-21 08:23 UTC, merged