feat(account): add action to update subscription features
myparcelnl/pdk pull request #133
Opened 2023-07-24 09:46 UTC by Mark-Ernst

2023-07-26 07:31 UTC, EdieLemoine requested changes
Ik mis tests

2023-07-26 07:31 UTC, EdieLemoine commented on src/Account/Model/Account.php
> +        'subscriptionFeatures' => 'array',
Graag als Collection, hoeft niet per se een custom collection te zijn als het een plat lijstje met strings is

2023-07-26 07:31 UTC, EdieLemoine commented on config/actions.php
> +         * Fetch subscription features
```suggestion
         * Fetch subscription features from the API.
```

2023-07-26 07:31 UTC, EdieLemoine commented on src/App/Action/Backend/Account/FetchSubscriptionFeaturesAction.php
> +        return new JsonResponse($this->subscriptionFeaturesRepository->getSubscriptionFeatures());
de wrapper property van de request mist hier, dit zou de frontend nu niet kunnen gebruiken mochten we dat willen

2023-07-26 07:31 UTC, EdieLemoine commented on src/App/Request/Account/FetchSubscriptionFeaturesEndpointRequest.php
> +        return 'subscription_features';
dit is voor post methods

2023-09-01 15:06 UTC, EdieLemoine approved these changes

2023-09-01 15:09 UTC, joerivanveen approved these changes

2023-09-04 06:24 UTC, merged