fix: fix weight not having impact on package type calculation
myparcelnl/pdk pull request #147
Opened 2023-08-07 09:21 UTC by Mark-Ernst

2023-08-07 09:28 UTC, EdieLemoine requested changes

2023-08-07 09:28 UTC, EdieLemoine commented on src/App/Cart/Service/CartCalculationService.php
> +                        && $this->isWeightUnderPackageTypeLimit($cart, $packageTypeName);
je hebt deze functie mooi generiek gemaakt, maar moet je die dan niet altijd uitvoeren, ook als het geen mailbox is?

2023-08-07 09:28 UTC, EdieLemoine commented on src/App/Cart/Service/CartCalculationService.php
> +            }, 0) <= Pdk::get(sprintf('%sWeightMaximum', $packageType));
Om dit netter te maken kan je denk ik beter die variabele in de config een array maken:

```
	`packageTypeWeightLimits' => value([
			DeliveryOptions::PACKAGE_TYPE_MAILBOX_NAME => 2000,
			// ... etc
	]),
```

En dan `Arr::get(Pdk::get('packageTypeWeightLimits'), $packageType))`. Dan hoeven ze niet eens allemaal te bestaan, dan krijgt hij een auto fallback naar null. (Die je zou kunnen aanpassen via de 2e param van `Arr::get`)

En nóg mooier is als je die reduce functie toevoegt aan de `PdkOrderLineCollection` als `getTotalWeight` oid.

2023-08-09 11:14 UTC, EdieLemoine requested changes

2023-08-09 11:14 UTC, EdieLemoine commented on src/App/Cart/Service/CartCalculationService.php
> +                20000
Geen random-maar-toch-logische waarde gebruiken, doe dan `INF`. En zet dit `Arr::get` brok even in een variabele, dit is slecht leesbaar.

2023-08-09 11:14 UTC, EdieLemoine commented on src/App/Cart/Service/CartCalculationService.php
> +                if (! $this->isWeightUnderPackageTypeLimit($cart, $packageTypeName)) {
Om hier een negated condition te vermijden, zou ik dan de functie zelf omdraaien.

En je gebruikt nu niet `$lineHasPackageType`, dus of die moet je wel gebruiken, of die assignment moet onder deze if statement.

2023-08-09 11:16 UTC, EdieLemoine approved these changes

2023-08-10 06:59 UTC, wthijmen approved these changes

2023-08-10 07:00 UTC, merged