fix(carriers): sort in preferred order for displaying names
myparcelnl/pdk pull request #152
Opened 2023-08-09 15:20 UTC by Mark-Ernst

2023-08-10 10:43 UTC, EdieLemoine requested changes

2023-08-10 10:43 UTC, EdieLemoine commented on config/pdk-default.php
> +    'sortOrderCarriers' => value([
die cijfers zijn niet nodig, de volgorde van de array is de volgorde. Plus, die volgorde kan beter bepaald worden per platform (zie `allowedCarriers` in platform configs). Dan heb je ook geen extra entry nodig en kan je die data gewoon laten leiden

2023-08-10 10:43 UTC, EdieLemoine commented on src/Account/Service/AccountSettingsService.php
> +        usort($carriers, function (Carrier $carrier1, Carrier $carrier2) {
er zit een sorteerfunctie in de collection

2023-08-10 14:07 UTC, EdieLemoine requested changes

2023-08-10 14:07 UTC, EdieLemoine commented on config/platform/myparcel.php
> +    'sortOrderCarriers' => [
dit is niet wat ik bedoel, nu zit je alsnog een extra property toe te voegen en werkt dit niet voor de andere platformen. ik bedoel dat je de `allowedCarriers` array in de juiste volgorde zet en zorgt dat dat dus ook de volgorde bepaalt.

2023-08-11 13:33 UTC, joerivanveen approved these changes

2023-08-11 13:34 UTC, merged