feat: save barcode in order note
myparcelnl/pdk pull request #155
Opened 2023-08-11 08:53 UTC by joerivanveen

2023-08-25 12:27 UTC, EdieLemoine requested changes

2023-08-25 12:27 UTC, EdieLemoine commented on config/pdk-settings.php
> +        return static function (int $shippingId) {
shipmentId

2023-08-25 13:17 UTC, EdieLemoine approved these changes

2023-08-28 07:21 UTC, Mark-Ernst approved these changes

2023-08-28 07:23 UTC, merged