fix(settings): changed order status digitalstamp field to select
myparcelnl/pdk pull request #177
Opened 2023-09-07 07:45 UTC by wthijmen

2023-09-07 08:36 UTC, Mark-Ernst approved these changes

2023-09-07 08:41 UTC, EdieLemoine requested changes

2023-09-07 08:52 UTC, wthijmen commented on src/Frontend/View/OrderSettingsView.php
> +                    'options' => $orderStatusesWithNone,
@EdieLemoine Ja, aangezien hij beschikbaar moest zijn in de OrderSettingsView & de GeneralSettingsView

2023-09-08 07:26 UTC, closed without merging

2023-09-08 07:26 UTC, EdieLemoine commented
wordt weggehaald