fix(label-description): limit to max length
myparcelnl/pdk pull request #190
Opened 2023-09-14 08:43 UTC by Mark-Ernst

2023-09-14 08:45 UTC, wthijmen approved these changes

2023-09-15 08:33 UTC, EdieLemoine requested changes

2023-09-15 08:33 UTC, EdieLemoine commented on src/App/Order/Calculator/General/LabelDescriptionCalculator.php
> +        return substr(
`Str::limit`, en dan liever het resultaat van `preg_replace_callback_array` even in een variabele zetten om het extra indent level te vermijden en het leesbaarder te maken

2023-09-15 08:33 UTC, EdieLemoine commented on tests/Unit/App/Order/Calculator/General/LabelDescriptionCalculatorTest.php
> +        ->toBeLessThanOrEqual(Pdk::get('labelDescriptionMaxLength'));
nice!

2023-09-15 08:33 UTC, EdieLemoine commented on tests/Unit/App/Order/Calculator/General/LabelDescriptionCalculatorTest.php
>          'order with multiple label description placeholders' => [
ik zou deze test ff in tweeën (of drieën) splitten, zodat je weet dat alle properties doorkomen én nogmaals de check dat het idd afgeknipt wordt

2023-09-15 08:34 UTC, EdieLemoine requested changes

2023-09-15 08:34 UTC, EdieLemoine commented on src/App/Order/Calculator/General/LabelDescriptionCalculator.php
> +            Pdk::get('labelDescriptionMaxLength')
Er is niet maar 1 max length, de carriers hebben hun eigen waarde hiervoor

2023-09-18 09:47 UTC, joerivanveen approved these changes

2023-09-29 08:26 UTC, EdieLemoine approved these changes

2023-09-29 08:57 UTC, merged