feat(orders): change status after creating label
myparcelnl/pdk pull request #196
Opened 2023-09-15 12:54 UTC by Mark-Ernst

2023-09-15 14:37 UTC, EdieLemoine requested changes

2023-09-18 11:39 UTC, Mark-Ernst commented on src/App/Action/Backend/Order/UpdateOrderStatusAction.php
> +            return new Response('No status to update', Response::HTTP_OK);
no content

2023-09-18 11:40 UTC, Mark-Ernst commented on src/App/Order/Contract/OrderStatusServiceInterface.php
> +     * @param        $status
types checken en goedzetten

2023-09-18 11:45 UTC, Mark-Ernst commented on tests/Unit/App/Action/Backend/Order/UpdateOrderStatusActionTest.php
> +    $orders = factory(PdkOrderCollection::class)
```suggestion
    $orders = factory(PdkOrderCollection::class, 1)
```

dan kan die 

```php
        ->push(
            factory(PdkOrder::class)
        )
``` 

weg

2023-09-19 09:27 UTC, EdieLemoine requested changes

2023-09-19 09:27 UTC, EdieLemoine commented on src/App/Action/Backend/Order/AbstractOrderAction.php
> +    protected $orderStatusService;
niet hier doen, nu hebben alle ongerelateerde actions ook deze injectie terwijl dat helemaal niet nodig is. Alleen injecten in de actie die dit gaat gebruiken

2023-09-19 09:27 UTC, EdieLemoine commented on tests/Unit/App/Action/Backend/Order/PrintOrderActionTest.php
> +    // Set this option to prevent error
niet doen :P

2023-09-19 09:43 UTC, EdieLemoine requested changes

2023-09-19 09:43 UTC, EdieLemoine commented on src/App/Action/Backend/Shipment/PrintShipmentsAction.php
> +    public function __construct(
terug op 1 regel

2023-09-19 09:43 UTC, EdieLemoine commented on src/App/Action/Backend/Order/UpdateOrderStatusAction.php
> +    public function __construct(
kan wss op 1 regel

2023-09-19 09:43 UTC, EdieLemoine commented on src/App/Action/Backend/Order/UpdateOrderStatusAction.php
> +        parent::__construct(
kan op 1 regel

2023-09-19 09:43 UTC, EdieLemoine commented on src/App/Action/Backend/Order/AbstractOrderAction.php
> +    public function __construct(
mag terug naar hoe het was

2023-09-19 09:43 UTC, EdieLemoine commented on src/App/Action/Backend/Order/SynchronizeOrdersAction.php
> +    public function __construct(
mag terug naar hoe het was

2023-09-19 11:03 UTC, joerivanveen approved these changes

2023-09-19 11:04 UTC, merged