fix(notifications): pass notifications to frontend
myparcelnl/pdk pull request #199
Opened 2023-09-21 10:33 UTC by joerivanveen

2023-09-21 11:40 UTC, EdieLemoine requested changes

2023-09-21 11:40 UTC, EdieLemoine commented on src/Notification/Model/Notification.php
> +        'tags'     => NotificationTags::class,
Ik denk dat dit beter (of net zo goed) een simpel object of array kan zijn. Het voelt een beetje als overkill, maar ook rigide om er een heel model voor te maken. Nu moet je dat steeds gaan uitbreiden als er ooit eens andere tags bij komen kijken, terwijl het ook prima een beetje een "black box" kan zijn, dat je de frontend laat kijken wat het ermee doet

2023-09-21 11:40 UTC, EdieLemoine commented on src/Notification/Service/NotificationService.php
> +     * @param  null|string[]         $content
dit moet `null|string|string[]` zijn

2023-09-21 11:40 UTC, EdieLemoine commented on src/Notification/Model/Notification.php
> + * @property string|null                                              $content
content mag een array of string van arrays zijn

2023-09-21 11:40 UTC, EdieLemoine commented on src/Notification/Model/Notification.php
>          'content'  => 'string',
Deze cast kan niet, dit was altijd dus al fout want hier moet ook een array in kunnen, je kan deze cast weghalen OF we kunnen ervoor kiezen dat we er hier in de backend altijd al een array van maken en dat die logica weg kan uit de frontend.

2023-09-21 11:40 UTC, EdieLemoine commented on src/Facade/Notifications.php
> + * @method static void add(string $title, string|string[] $content, string $level, ?string $category, ?Tags $tags)
de default values missen hier, daardoor zullen de facade methods altijd aangeven dat de laatste 2 params verplicht zijn

2023-09-21 11:40 UTC, EdieLemoine commented on src/Notification/Contract/NotificationServiceInterface.php
> +    public function add(?string $title, $content, string $variant, ?string $category, ?NotificationTags $tags): void;
de fallback values missen hier ook

2023-09-22 07:59 UTC, EdieLemoine approved these changes

2023-09-22 08:06 UTC, Mark-Ernst approved these changes

2023-09-22 09:38 UTC, merged