feat(carriers): add ups
myparcelnl/pdk pull request #202
Opened 2023-09-22 10:35 UTC by wthijmen

2023-09-22 12:06 UTC, EdieLemoine requested changes

2023-09-22 12:06 UTC, EdieLemoine commented on config/platform/myparcel.php
> +        [
ik mis de order schemas en dat hij ergens aan een platform toegevoegd wordt

2023-09-25 07:37 UTC, EdieLemoine approved these changes

2023-09-25 08:13 UTC, Mark-Ernst approved these changes

2023-09-25 08:16 UTC, merged