fix(calculator): ensure signature for dhl europlus orders
myparcelnl/pdk pull request #206
Opened 2023-09-26 13:47 UTC by Mark-Ernst

2023-09-27 12:34 UTC, EdieLemoine requested changes

2023-09-27 12:34 UTC, EdieLemoine commented on src/App/Order/Calculator/DhlEuroplus/DhlEuroplusShipmentOptionsCalculator.php
> +        parent::__construct($order);
deze constructor doet niks en kan weg

2023-09-27 12:34 UTC, EdieLemoine commented on src/App/Order/Calculator/DhlParcelConnect/DhlParcelConnectShipmentOptionsCalculator.php
> +        parent::__construct($order);
deze kan ook weg

2023-09-27 12:34 UTC, EdieLemoine commented on src/App/Order/Calculator/DhlEuroplus/DhlEuroplusShipmentOptionsCalculator.php
> + * - When evening delivery is enabled same-day delivery is not available
wat hier staat wordt niet gedaan

2023-09-27 12:34 UTC, EdieLemoine commented on src/App/Order/Calculator/DhlParcelConnect/DhlParcelConnectShipmentOptionsCalculator.php
> + * - Evening delivery is only allowed in the Netherlands.
wat hier staat wordt niet gedaan

2023-09-27 12:34 UTC, EdieLemoine commented on tests/Unit/App/Order/Calculator/General/CarrierSpecificCalculatorTest.php
> +                ->withSignature(0);
constante gebruiken

2023-09-27 12:34 UTC, EdieLemoine commented on tests/Unit/App/Order/Calculator/General/CarrierSpecificCalculatorTest.php
> +                ->withSignature(0);
constante gebruiken

2023-09-27 14:27 UTC, EdieLemoine approved these changes

2023-09-28 07:21 UTC, wthijmen approved these changes

2023-09-28 07:36 UTC, merged