fix(returns): fix faulty shipment options
myparcelnl/pdk pull request #208
Opened 2023-09-27 14:44 UTC by Mark-Ernst

2023-09-27 14:58 UTC, EdieLemoine requested changes
ik mis tests

2023-09-27 14:58 UTC, EdieLemoine commented on src/Shipment/Request/PostReturnShipmentsRequest.php
> +            return $result === -1 ? 0 : $result;
gebruik de tri state service hiervoor

2023-09-29 07:46 UTC, wthijmen approved these changes

2023-09-29 08:42 UTC, EdieLemoine approved these changes

2023-09-29 08:44 UTC, merged