fix: include address2 in street
myparcelnl/pdk pull request #214
Opened 2023-10-12 07:21 UTC by Mark-Ernst

2023-10-12 08:23 UTC, EdieLemoine requested changes
er zijn allemaal ongerelateerde snapshots aangepast, en ik mis een test die bevestigt dat dit correct in de `street` komt

2023-10-12 08:23 UTC, EdieLemoine commented on src/Shipment/Request/PostShipmentsRequest.php
> +        $street    = trim(implode(' ', [$recipient->address1, $recipient->address2])) ?: null;
null? dit veld is toch verplicht en moet altijd een string zijn?

2023-10-12 12:27 UTC, EdieLemoine requested changes

2023-10-12 12:27 UTC, EdieLemoine commented on tests/__snapshots__/CarrierTest__it_instantiates_carriers_from_name_with_(myparcel)__1.json
> +        "name": "dpd",
waar komt dit vandaan?

2023-10-12 13:49 UTC, EdieLemoine approved these changes

2023-10-13 07:47 UTC, joerivanveen approved these changes

2023-10-13 07:49 UTC, merged