fix(returns): prevent validation error on export return
myparcelnl/pdk pull request #216
Opened 2023-10-14 19:52 UTC by joerivanveen

INT-191

2023-10-16 07:56 UTC, Mark-Ernst approved these changes

2023-10-16 09:28 UTC, EdieLemoine approved these changes

2023-10-16 11:16 UTC, EdieLemoine requested changes
ik mis tests (of gewijzigde snapshots)

2023-10-19 13:31 UTC, EdieLemoine commented on tests/Unit/App/Action/Backend/Order/ExportReturnActionTest.php
> +                        [
heb je dit expres zo als arrays gedaan? want je kunt ook gewoon door chainen met `factory(Shipment::class)->withDeliveryOptions(factory(DeliveryOptions::class))` etc

2023-10-19 14:46 UTC, joerivanveen commented on src/Shipment/Request/PostReturnShipmentsRequest.php
> +    private function ensureReturnCapabilities(Shipment $shipment): Shipment
huh? die staat er wel?

2023-10-20 07:04 UTC, EdieLemoine approved these changes
super nice 🏭😎

2023-10-20 07:05 UTC, merged