feat(carriers): add features for platform belgie and myparcel
myparcelnl/pdk pull request #218
Opened 2023-10-18 11:42 UTC by Mark-Ernst

2023-10-19 11:30 UTC, joerivanveen approved these changes

2023-10-19 12:01 UTC, EdieLemoine requested changes
de titel is vrij onduidelijk

2023-10-19 12:01 UTC, EdieLemoine commented on config/platform/belgie.php
> +                    'insurance' => false,
waarom false? dit zou `[0]` moeten zijn als dat de enige geaccepteerde waarde is

2023-10-24 15:21 UTC, EdieLemoine approved these changes

2023-10-24 15:23 UTC, merged