feat: add calculator for dpd
myparcelnl/pdk pull request #219
Opened 2023-10-18 12:13 UTC by Mark-Ernst

2023-10-19 11:55 UTC, EdieLemoine requested changes

2023-10-19 11:55 UTC, EdieLemoine commented on config/pdk-business-logic.php
> +    'dpdInsuranceAmount' => value(52000),
dit kan niet hier, dit moet via de carrier configs lopen

2023-10-19 11:55 UTC, EdieLemoine commented on tests/Unit/App/Order/Calculator/General/CarrierSpecificCalculatorTest.php
> +    'when insurance is disabled, enable it anyway' => [
dit moet voor alle carriers werken, als insurance op default staat en er geen default is ingesteld oid moet er alsnog een waarde gekozen worden. zie hier al wel vaker export errors door

2023-10-24 09:44 UTC, wthijmen approved these changes

2023-11-14 13:47 UTC, EdieLemoine approved these changes

2023-11-14 13:47 UTC, EdieLemoine commented on src/Frontend/View/CarrierSettingsItemView.php
> +        return count($insuranceAmounts) > 1 ? [
dit is wel een beetje wonky, liever gewoon zoiets:

```php
if (empty($insuranceAmounts)) {
  return [];
}

// de rest
```

2023-11-14 14:01 UTC, merged