fix: fix error when status is null
myparcelnl/pdk pull request #221
Opened 2023-10-24 13:15 UTC by Mark-Ernst

2023-10-24 13:17 UTC, EdieLemoine requested changes
Ik mis tests en een scope in je titel. De titel beschrijft ook niet wanneer deze error optreedt

2023-10-24 15:18 UTC, EdieLemoine requested changes

2023-10-24 15:18 UTC, EdieLemoine commented on src/App/Action/Backend/Order/UpdateOrderStatusAction.php
> +        if (Settings::OPTION_NONE === (int) $status || null === $status) {
Waarom kan dit überhaupt null zijn? In de config kan je ervoor zorgen dat dingen standaard waarden krijgen vanuit installatie. `null` is weer een extra mogelijke waarde die we nu ook weer moeten afhandelen met allemaal enge codes.

Zie `builtInDefaultSettings` in de config. Dit is wss nodig voor alle tristate velden die niet null mogen zijn.

2023-10-25 10:09 UTC, EdieLemoine requested changes

2023-10-25 10:09 UTC, EdieLemoine commented on config/pdk-settings.php
> +                SettingsManager::KEY_ALL => [
dit kan niet, die key all is bedoeld voor collection settings, zoals carrier settings. nu gaat hij dit doen:

`orderSettings.*.statusOnLabelCreate`

+ dit moet ook voor de andere tristate opties, begin maar met de andere status update settings hier

En `-1` moet die tristate const zijn

2023-10-26 07:24 UTC, wthijmen approved these changes

2023-10-26 08:51 UTC, EdieLemoine approved these changes

2023-10-26 08:53 UTC, merged