fix(webhooks): add event to hook
myparcelnl/pdk pull request #225
Opened 2023-10-27 07:39 UTC by wthijmen

INT-212

2023-10-27 07:48 UTC, joerivanveen approved these changes

2023-10-27 07:55 UTC, Mark-Ernst commented on src/App/Webhook/PdkWebhookManager.php
> +        if (isset($headers['x-myparcel-hook'])) {
Ik zou hier ff een unhappy path eerst doen

2023-10-27 07:55 UTC, Mark-Ernst commented on src/App/Webhook/PdkWebhookManager.php
> +            $body['data']['hooks'] = array_map(function ($hook) use ($headers) {
Het is denk ik mooier om het resultaat van deze map in een losse variabele te zetten (bijvoorbeeld $hooks ofzo) ipv de body te modificeren en vervolgens te returnen

2023-10-27 11:59 UTC, Mark-Ernst approved these changes

2023-10-27 13:25 UTC, EdieLemoine requested changes
ik mis tests

2023-11-02 08:26 UTC, EdieLemoine requested changes

2023-11-02 08:26 UTC, EdieLemoine commented on src/App/Webhook/PdkWebhookManager.php
> +            return $body['data']['hooks'] ?? [];
je doet nu 2x `$body['data']['hooks']`, dat hoeft niet, graag in een variabele zetten. en de onderste is niet null safe

2023-11-02 08:26 UTC, EdieLemoine commented on tests/Unit/App/Webhook/PdkWebhookManagerTest.php
> +                    array_merge(['event' => $hook]),
merge is niet nodig

2023-11-02 08:26 UTC, EdieLemoine commented on tests/Unit/App/Webhook/PdkWebhookManagerTest.php
> +    $cronService->executeAllTasks();
waarom run je ze als je niet kijkt naar het resultaat? nu ben je de cron service aan het testen. je kunt wel kijken of het uiteindelijk de juiste action aanroept

2023-11-02 08:26 UTC, EdieLemoine commented on src/App/Webhook/PdkWebhookManager.php
> +        $headers = $request->headers->all();
waarom wordt dit allemaal gedaan? webhooks hebben al een event erin

```json
{
  "data": {
    "hooks": [
      {
        "shipment_id": ...,
        "account_id": ...,
        "shop_id": ...,
        "status": ...,
        "barcode": "...",
        "shipment_reference_identifier": "",
        "event": "shipment_status_change"
      }
    ]
  }
}
```

2023-11-02 08:26 UTC, EdieLemoine commented on src/App/Webhook/PdkWebhookManager.php
> +        if (! isset($headers['x-myparcel-hook'])) {
gebruik `$request->headers->get()`

2023-11-02 08:26 UTC, EdieLemoine commented on src/App/Webhook/PdkWebhookManager.php
> +        $logContext = ['request' => get_object_vars($request)];
Waarom check je de url niet? Nu heeft de hash geen zin meer en mag iedereen webhooks sturen naar andermans website. De hash is voor security.

2023-11-08 08:25 UTC, Mark-Ernst approved these changes

2023-11-08 09:09 UTC, EdieLemoine requested changes

2023-11-08 09:09 UTC, EdieLemoine commented on src/App/Webhook/PdkWebhookManager.php
> +            $hook['event'] = $myParcelHeader;
zoals eerder gezegd, laat de bestaande event staan en vervang die door de header als ie niet aanwezig is 

```suggestion
            $hook['event'] = hook['event'] ?? $myParcelHeader;
```

2023-11-08 09:09 UTC, EdieLemoine commented on tests/Unit/App/Webhook/PdkWebhookManagerTest.php
> +    $logger = Pdk::get(LoggerInterface::class);
dit wordt niet gebruikt

2023-11-08 09:09 UTC, EdieLemoine commented on tests/Unit/App/Webhook/PdkWebhookManagerTest.php
> +})->with(WebhookSubscription::ALL);
die header ja/nee kan je gewoon in een test argument stoppen, je hebt nu 44 regels code gedupliceerd terwijl dat er gewoon bij in kan in 1 test

```php
->with(WebhookSubscription::ALL)
->with([
  'no header' => [false],
  'header'    => [true]
]);
````

2023-11-08 09:09 UTC, EdieLemoine commented on tests/Unit/App/Webhook/PdkWebhookManagerTest.php
> +    expect($response->getStatusCode())
Je test helemaal niet of dit werkt en de webhook succesvol geparsed wordt, je bent nu alleen maar aan het kijken of er een webhook geregistreerd is. Er wordt nu niet getest of dat header/event stuk werkt. Vandaar ook dat het niet werkt in je code maar je tests wel slagen.

2023-11-08 12:56 UTC, EdieLemoine approved these changes

2023-11-08 12:59 UTC, merged