feat: add audits
myparcelnl/pdk pull request #236
Opened 2023-11-10 10:33 UTC by Mark-Ernst

2023-11-16 12:46 UTC, joerivanveen approved these changes

2023-11-20 12:58 UTC, EdieLemoine requested changes

2023-11-20 12:58 UTC, EdieLemoine commented on src/App/Api/Service/PdkActionsService.php
> +    public function executeAutomatic($action, array $parameters = []): Response
phpdoc

2023-11-20 12:58 UTC, EdieLemoine commented on src/Audit/Model/Audit.php
> + * @property null|string              $type
is niet nullable

2023-11-20 12:58 UTC, EdieLemoine commented on src/Audit/Model/Audit.php
> + * @property null|array               $arguments
is niet nullable

2023-11-20 12:58 UTC, EdieLemoine commented on src/Audit/Service/AuditService.php
> +    public function allByModel(string $model, string $identifier): AuditCollection
deze mist in de interface

2023-11-20 12:58 UTC, EdieLemoine commented on src/Audit/Service/AuditService.php
> +     * @param  string $model
`class-string<Model>`

2023-11-20 12:58 UTC, EdieLemoine commented on src/App/Api/Service/PdkActionsService.php
> +    public function executeAutomatic($action, array $parameters = []): Response
dit mist in de interface

2023-11-20 12:58 UTC, EdieLemoine commented on src/App/Audit/Concern/HasAudits.php
> +    public function addAudit(string $action, ?string $type = null, ?array $arguments = null): void
waarom null op $arguments? gewoon alleen array supporten en defaulten naar lege array

2023-11-20 12:58 UTC, EdieLemoine commented on src/App/Order/Model/PdkOrder.php
> +        $this->initializeHasAudits();
dit moet in model verwerkt worden, op de manier die ik je heb laten zien. dit kan je niet handmatig gaan aanroepen, is te foutgevoelig

2023-11-20 12:58 UTC, EdieLemoine commented on tests/Unit/App/Api/Service/PdkActionsServiceTest.php
> +it('executes action automatically', function () {
dit beschrijft niet wat het doet, er gebeurt niks automatisch, je markeert het alleen zo

2023-11-20 12:58 UTC, EdieLemoine commented on src/Audit/Repository/AbstractAuditRepository.php
> +    abstract public function all(): AuditCollection;
dit heeft geen zin, deze hele class kan weg. dit staat al in de interface

2023-11-20 12:58 UTC, EdieLemoine commented on tests/Unit/Audit/Service/AuditServiceTest.php
> +});
ik mis de test voor allByModel

2023-11-20 12:58 UTC, EdieLemoine commented on tests/factories/Audit/Model/AuditFactory.php
> +     * @param  \MyParcelNL\Pdk\Audit\Model\Audit $model
gebruik `T`

2023-11-20 12:58 UTC, EdieLemoine commented on src/Audit/Contract/AuditRepositoryInterface.php
> +     * @param  \MyParcelNL\Pdk\Audit\Model\Audit $audit
die `@param` en `@return` hoeven hier niet

2023-11-21 13:50 UTC, EdieLemoine requested changes

2023-11-21 13:50 UTC, EdieLemoine commented on composer.json
> -    "name": "myparcelnl/pdk",
dit moet terug

2023-11-21 13:50 UTC, EdieLemoine commented on src/App/Audit/Concern/HasAudits.php
> +            throw new InvalidArgumentException('Audit identifier is not set');
dit is niet gecovered

2023-11-21 13:50 UTC, EdieLemoine commented on src/Base/Model/Model.php
> +     * @var array|mixed
hoezo array of mixed?

2023-11-21 13:50 UTC, EdieLemoine commented on src/Base/Model/Model.php
> +            $baseName = (new ReflectionClass($trait))->getShortName();
Je moet reflection in prod code vermijden ivm performance. Hier is `Utils::classBasename ` voor

2023-11-21 13:50 UTC, EdieLemoine commented on src/Base/Model/Model.php
> +        if (! isset(static::$booted[static::class])) {
unhappy flow eerst

2023-11-21 13:50 UTC, EdieLemoine commented on src/Base/Model/Model.php
> +        $this->bootIfNotBooted();
moet dit niet helemaal bovenaan?

2023-11-21 13:50 UTC, EdieLemoine commented on tests/Unit/Base/Model/ModelTraitsTest.php
> +        ->toBe('Mokka');
```suggestion
        ->toBe('Mocha');
```

2023-11-21 13:50 UTC, EdieLemoine commented on tests/Mocks/MockHasCatsTrait.php
> +        $this->attributes['cat1'] = 'Gouda';
🥺🥺🥺🥺🥺

2023-11-21 13:50 UTC, EdieLemoine commented on tests/Mocks/MockHasCatsTrait.php
> +        $this->attributes['cat2'] = 'Mokka';
```suggestion
        $this->attributes['cat2'] = 'Mocha';
```

2023-11-21 13:50 UTC, EdieLemoine commented on src/Base/Model/Model.php
> +    public static $booted;
```suggestion
    public static $booted = [];
```

2023-11-21 13:50 UTC, EdieLemoine commented on src/Base/Model/Model.php
> +    public static $booted;
moet dit echt public zijn?

2023-11-21 16:28 UTC, EdieLemoine approved these changes

2023-11-21 16:30 UTC, merged