feat: add shipments
myparcelnl/pdk pull request #24
Opened 2022-07-27 12:21 UTC by EdieLemoine

2022-07-28 11:43 UTC, wthijmen requested changes

2022-07-28 11:43 UTC, wthijmen commented on src/Shipment/Model/RetailLocation.php
> +
Moeten deze casts niet weg omdat die in de construct gedaan wordt?

2022-07-28 11:43 UTC, wthijmen commented on tests/Unit/Service/DeliveryOptionsMergerTest.php
>  use MyParcelNL\Sdk\src\Model\Carrier\CarrierInstabox;
Deze sdk import kan weg

2022-07-28 11:43 UTC, wthijmen commented on tests/Unit/Service/DeliveryOptionsMergerTest.php
>                  'carrier'         => CarrierInstabox::NAME,
CarrierOptions::CARRIER_INSTABOX_NAME

2022-07-28 11:43 UTC, wthijmen commented on tests/Unit/Service/DeliveryOptionsMergerTest.php
>                  'carrier'         => CarrierInstabox::NAME,
CarrierOptions::CARRIER_INSTABOX_NAME

2022-07-28 12:02 UTC, joerivanveen approved these changes

2022-07-28 14:04 UTC, joerivanveen approved these changes

2022-07-28 14:38 UTC, wthijmen approved these changes

2022-07-29 08:28 UTC, wthijmen approved these changes

2022-07-29 13:18 UTC, joerivanveen approved these changes

2022-07-29 13:19 UTC, merged