feat: add package type packet
myparcelnl/pdk pull request #249
Opened 2024-02-06 09:25 UTC by Mark-Ernst

2024-03-04 12:22 UTC, wthijmen approved these changes

2024-03-05 09:17 UTC, joerivanveen requested changes

2024-03-05 09:17 UTC, joerivanveen commented on config/schema/myparcel/order/postnl/row_package_small.json
> +  "description": "myparcel/order/postnl/row_package",
```suggestion
  "description": "myparcel/order/postnl/row_package_small",
```

2024-03-05 09:17 UTC, joerivanveen commented on src/App/DeliveryOptions/Service/DeliveryOptionsService.php
> +        $minimumDropOffDelay = -1 === $cart->shippingMethod->minimumDropOffDelay
Dit lijkt een bugfix die in een aparte PR hoort? Negeer dit als ik het verkeerd heb.

2024-03-05 09:17 UTC, joerivanveen commented on tests/Unit/App/Action/Backend/Order/ExportOrderActionTest.php
> +    $contents = $lastRequest->getBody()
Waarom deze extra variabele introduceren, is dat een per ongeluk refactor?

2024-03-05 09:17 UTC, joerivanveen commented on tests/__snapshots__/ValidationTest__it_validates_order_with_data_set_dhlforyou_to_France__1.json
> +{
Dit lijkt niet de bedoeling, maar ik heb niet het project binnengehaald nog, is het logisch dat deze foutmelding komt uit deze test?

2024-03-05 10:05 UTC, joerivanveen approved these changes

2024-03-05 10:09 UTC, merged