feat: add delivery date service
myparcelnl/pdk pull request #25
Opened 2022-08-01 20:55 UTC by joerivanveen

2022-08-03 06:58 UTC, wthijmen requested changes

2022-08-03 06:58 UTC, wthijmen commented on src/Service/DeliveryDateService.php
> +/** @noinspection PhpUndefinedMethodInspection */
Deze kan weg

2022-08-03 06:58 UTC, wthijmen commented on src/Service/DeliveryDateService.php
> +    public static function getDeliveryDays(DateTime $today): DropOffDayCollection
docblocks

2022-08-03 06:58 UTC, wthijmen commented on src/Service/DeliveryDateService.php
> +    private static function mergeDropOffDayPossibilities(DropOffDay $dropOffDay, DropOffDay $exceptionDay): DropOffDay
docblocks

2022-08-03 06:58 UTC, wthijmen commented on src/Service/DeliveryDateService.php
> +    private static function getExceptionDays(
docblocks

2022-08-03 06:58 UTC, wthijmen commented on tests/Bootstrap/MockSettings.php
> +    public function get(string $key)
docblocks

2022-08-04 07:51 UTC, EdieLemoine commented on src/Service/DeliveryDateService.php
> +/** @noinspection PhpUndefinedMethodInspection */
geen warnings hiden, je moet je helper file regeneraten door composer update te runnen

2022-08-04 08:46 UTC, EdieLemoine requested changes
morgenochtend even samen zitten om hem te proberen te refactoren :)

2022-08-04 08:46 UTC, EdieLemoine commented on src/Service/DeliveryDateService.php
> +    private static function mergeDropOffDayPossibilities(DropOffDay $dropOffDay, DropOffDay $exceptionDay): DropOffDay
misschien in de naam verwerken dat dit de uitzonderingen merged

2022-08-04 08:46 UTC, EdieLemoine commented on src/Service/DeliveryDateService.php
> +            $exceptionDateCollection = $exceptionDays->where('date', '==', $dropOffDay->date);
hier kan je firstWhere gebruiken, dan kan de hele collection shizzle weg en krijg je direct een DropOffDay in die method

2022-08-04 08:46 UTC, EdieLemoine commented on src/Service/DeliveryDateService.php
> +        return new DropOffDay($mergedDropOffDays);
deze functie is niet zo duidelijk, het klinkt alsof je meerdere dropoffdays combineert tot nog meer dropoffdays en dat in 1 dropoffday aan het proppen bent

2022-08-04 08:46 UTC, EdieLemoine commented on src/Service/DeliveryDateService.php
> +        /** @var \MyParcelNL\Pdk\Shipment\Collection\DropOffDayCollection $dropOffDays */
niet nodig als je je helper gewoon rebuild

2022-08-04 08:46 UTC, EdieLemoine commented on src/Carrier/Model/DropOffDayPossibilities.php
> +        'dropOffDays'          => null,
kunnen deze niet geinitieerd worden als DropOffDayCollection? zou een hoop null checks schelen

2022-08-04 08:46 UTC, EdieLemoine commented on src/Service/DeliveryDateService.php
> +        }
als hierboven een irregularity wordt gegooid, moet je dan wel `$deliveryDateObject` clonen?

2022-08-04 08:46 UTC, EdieLemoine commented on src/Service/DeliveryDateService.php
> +        $oldDate->setTime(0, 0);
het lijkt erop dat deze niet wordt gebruikt..?

2022-08-04 08:46 UTC, EdieLemoine commented on src/Service/DeliveryDateService.php
> +    public static function fixPastDeliveryDate($deliveryDate): string
misschien deze ook een betere naam?

2022-08-04 08:46 UTC, EdieLemoine commented on src/Service/DeliveryDateService.php
> +        $tomorrow = new DateTime('tomorrow');
kun je kijken om waar mogelijk DateTimeImmutable te gebruiken? Hier kan je dat bijvoorbeeld doen en dan wordt de tijd al 00:00:00, dus de latere setTime was helemaal niet nodig.

2022-08-08 10:51 UTC, EdieLemoine submitted a review, later dismissed

2022-08-08 10:59 UTC, wthijmen submitted a review, later dismissed

2022-08-08 11:01 UTC, wthijmen approved these changes

2022-08-08 12:01 UTC, merged