fix(calculator): disable shipment options for postnl pickup
myparcelnl/pdk pull request #252
Opened 2024-02-13 13:26 UTC by Mark-Ernst

INT-365

2024-02-14 08:19 UTC, wthijmen approved these changes

2024-02-14 13:56 UTC, EdieLemoine approved these changes

2024-02-14 13:56 UTC, EdieLemoine requested changes
waarom zijn er geen tests aangepast?

2024-02-15 15:02 UTC, EdieLemoine approved these changes

2024-02-15 15:05 UTC, merged