fix: maxInsuranceValue fix
myparcelnl/pdk pull request #283
Opened 2024-06-25 08:03 UTC by GravendeelJochem

INT-531

2024-06-26 14:06 UTC, EdieLemoine requested changes
tests missen, titel is niet goed

2024-06-27 15:16 UTC, joerivanveen requested changes
- Vanwege de verwarring zou ik in de tests de bedragen die achter het euro teken staan daadwerkelijk in euro’s noemen, voor de leesbaarheid.
- Klopt deze story nu met de werking van de keuzes, cq zijn de keuzes die gemaakt (kunnen) worden nu al in centen?
- Graag in de titel beschrijven (in gebiedende wijs) welk probleem je opgelost hebt.

2024-07-03 07:38 UTC, GravendeelJochem commented
> * Vanwege de verwarring zou ik in de tests de bedragen die achter het euro teken staan daadwerkelijk in euro’s noemen, voor de leesbaarheid.
> * Klopt deze story nu met de werking van de keuzes, cq zijn de keuzes die gemaakt (kunnen) worden nu al in centen?
> * Graag in de titel beschrijven (in gebiedende wijs) welk probleem je opgelost hebt.

- Titel is aangepast
- Ja de story klopt nog.

2024-07-04 09:03 UTC, joerivanveen approved these changes

2024-07-04 09:42 UTC, EdieLemoine approved these changes

2024-07-05 14:53 UTC, merged