fix(webhooks): always refresh base url on regeneration of webhooks
myparcelnl/pdk pull request #293
Opened 2024-08-09 15:08 UTC by EdieLemoine

2024-08-12 08:12 UTC, CherMyParcel approved these changes

2024-08-12 08:25 UTC, FlorianSDV approved these changes

2024-08-12 08:53 UTC, GravendeelJochem approved these changes

2024-08-13 07:31 UTC, joerivanveen requested changes
Die TAR file uit de docker-cache hoort er niet bij toch?? Verder helemaal akkoort, mooie versimpeling wmb

2024-08-14 09:28 UTC, EdieLemoine commented
@GravendeelJochem huh! dat is raar, ik haal hem weg

2024-08-14 09:45 UTC, GravendeelJochem approved these changes

2024-08-15 07:10 UTC, joerivanveen approved these changes

2024-08-15 10:25 UTC, merged