feat(webhooks): link shipment to order
myparcelnl/pdk pull request #327
Opened 2024-12-05 13:57 UTC by joerivanveen

Allows showing shipment details including barcode in order mode, when label is printed in backoffice.

INT-627

2024-12-11 09:02 UTC, FreekVR requested changes

2024-12-11 09:02 UTC, FreekVR commented on tests/Unit/App/Webhook/Hook/ShipmentStatusChangeWebhookTest.php
> +]);
Please restore empty newline end-of-file

2024-12-11 09:02 UTC, FreekVR commented on tests/Unit/App/Order/Repository/AbstractPdkOrderRepositoryTest.php
> +});
Please restore empty newline end-of-file

2024-12-11 09:07 UTC, FreekVR commented
Commit message covers the end-user feature but not really the changes in this repo.

Suggest to change it to (as I understand these changes, please correct if not right)

```
feat: improved linking shipments to orders

allows showing barcode when printed from backoffice #327
```

2024-12-11 20:26 UTC, joerivanveen commented on src/App/Action/Backend/Shipment/UpdateShipmentsAction.php
> +        if ($request->get('linkFirstShipmentToFirstOrder')) {
Done.

2024-12-11 20:26 UTC, joerivanveen commented on src/App/Order/Repository/AbstractPdkOrderRepository.php
> +    public function getByApiIdentifier(string $uuid): ?PdkOrder
Done.

2024-12-11 20:27 UTC, joerivanveen commented on src/App/Webhook/Hook/ShipmentStatusChangeWebhook.php
> +        $order = Pdk::get(PdkOrderRepositoryInterface::class)->getByApiIdentifier($content['order_id']);
Done.

2024-12-16 12:43 UTC, FreekVR approved these changes

2024-12-16 13:58 UTC, GravendeelJochem approved these changes

2024-12-17 08:50 UTC, merged