feat: add validation to pdk orders
myparcelnl/pdk pull request #36
Opened 2022-09-01 18:52 UTC by joerivanveen

2022-09-08 08:55 UTC, EdieLemoine requested changes

2022-09-08 08:55 UTC, EdieLemoine commented on config/orderValidator.php
> +                            true => [
true als key? dit is best wel "raar en eng" en gaat ook fout wanneer er waarden komen die niet als key kunnen. ik weet dat we nog vastzitten aan een oude json schema draft, maar als je dit toch op json schema wil laten lijken, implementeer dan zelf die if/then/else logica https://json-schema.org/understanding-json-schema/reference/conditionals.html#id6

2022-09-08 08:55 UTC, EdieLemoine commented on config/schema/order.json
> +    "deliveryOptions": {
dit ziet er niet compleet uit

2022-09-08 08:55 UTC, EdieLemoine commented on src/Validation/Validator.php
> +        $orderArray['deliveryOptions']['shipmentOptions'] = $this->convertNullValuesInShipmentOptions(
waarom als array? Je hebt nu een extra functie, moet daarin convertNullValuesInShipmentOptions allemaal logica die niks met deze class te maken heeft vastleggen en een loop doen.

je kunt ook zoiets doen: 

```php
    $shipmentOptions->fill([
        'ageCheck'        => (bool) $shipmentOptions->ageCheck,
        'insurance'       => (int) $shipmentOptions->insurance,
        'largeFormat'     => (bool) $shipmentOptions->largeFormat,
        'onlyRecipient'   => (bool) $shipmentOptions->onlyRecipient,
        'return'          => (bool) $shipmentOptions->return,
        'sameDayDelivery' => (bool) $shipmentOptions->sameDayDelivery,
        'signature'       => (bool) $shipmentOptions->signature,
    ]);
```
of nog beter, voeg een method toe aan de ShipmentOptions class die dit doet. misschien willen we wel vaker alle waarden "vastleggen"

2022-09-08 08:55 UTC, EdieLemoine commented on src/Validation/Validator.php
> +        return $validator->isValid();
ik mis nu de mogelijkheid om te kijken wat er precies fout was, dat gaan we wel heel hard nodig hebben

2022-09-08 08:55 UTC, EdieLemoine commented on src/Validation/Validator.php
> +        $countryService = $order->recipient->cc;
dit is een country, niet een service

2022-09-08 08:55 UTC, EdieLemoine commented on src/Validation/Validator.php
> +        if (! isset($this->extras[$what])) {
what?

2022-09-08 08:55 UTC, EdieLemoine commented on src/Validation/Validator.php
> +     * @param         $value
mixed

2022-09-08 08:55 UTC, EdieLemoine commented on src/Validation/Validator.php
> +        $this->schema = Config::get('schema/order');
die `$this->... = ...` stuff kan in de constructor

2022-09-08 08:55 UTC, EdieLemoine commented on src/Validation/Validator.php
> +     * @var PdkOrder
FQCN

2022-09-08 08:55 UTC, EdieLemoine commented on src/Validation/Validator.php
> +    private const DEFAULT_CARRIER  = 'postnl';
CarrierOptions

2022-09-08 08:55 UTC, EdieLemoine commented on src/Validation/Validator.php
> +    private const DEFAULT_PLATFORM = 'myparcel';
config/platform.php

2022-09-08 08:55 UTC, EdieLemoine commented on src/Validation/Validator.php
> +     * @param  PdkOrder $order
FQCN

2022-09-08 08:55 UTC, EdieLemoine commented on src/Validation/Validator.php
> +    private function adjustSchemaToRequirements(): void
ik vind dit niet echt duidelijk

2022-09-08 08:55 UTC, EdieLemoine commented on src/Validation/Validator.php
> +        if (in_array($countryService, CountryService::EU_COUNTRIES, true)) {
Dit hoort in de countryservice, daar moet je methods hebben om te kijken of iets domestic, eu of row is. 

Om BE af te vangen, misschien per platform definiëren (in de platform config) wat "speciale" landen zijn zodat we niet van die idiote "isNl" of "isBe" functies krijgen, maar dat je via die weg landen kunt invoeren die individueel verwerkt moeten worden

2022-09-14 08:09 UTC, Mark-Ernst commented on config/orderValidator.php
> +                                                    'weight' => [
Ongefrankeerd heeft in principe geen gewichtslimiet

2022-09-14 09:13 UTC, wthijmen approved these changes

2022-09-30 08:18 UTC, wthijmen submitted a review, later dismissed

2022-09-30 14:21 UTC, EdieLemoine approved these changes

2022-09-30 14:22 UTC, Mark-Ernst approved these changes

2022-09-30 14:22 UTC, merged