feat: add product settings
myparcelnl/pdk pull request #38
Opened 2022-09-06 14:15 UTC by Mark-Ernst

2022-09-08 07:10 UTC, joerivanveen submitted a review, later dismissed

2022-09-08 08:26 UTC, EdieLemoine requested changes
Ik mis de class(es) om deze data op te halen. Zie https://github.com/myparcelnl/pdk/pull/37

2022-09-08 08:26 UTC, EdieLemoine commented on src/Settings/Model/ProductSettings.php
> +        self::CUSTOMS_CODE             => '',
lege string??

2022-09-19 12:27 UTC, EdieLemoine approved these changes

2022-09-19 14:11 UTC, EdieLemoine approved these changes

2022-09-19 14:12 UTC, merged