feat(actions): add print order action
myparcelnl/pdk pull request #44
Opened 2022-11-03 10:44 UTC by joerivanveen

2022-11-03 10:49 UTC, EdieLemoine requested changes

2022-11-03 10:49 UTC, EdieLemoine commented on src/Plugin/Action/Order/PrintOrderAction.php
> +        $method = isset($parameters['downloadPdf']) && $parameters['downloadPdf'] ? 'fetchLabelPdf' : 'fetchLabelLink';
liever `download` dan `downloadPdf`

2022-11-03 10:49 UTC, EdieLemoine commented on src/Plugin/Action/Order/PrintOrderAction.php
> +                $parameters['downloadDisplay'] ?? 'a6',
`display` ipv `downloadDisplay`, en er is wel ergens een const voor "a6" lijkt me

2022-11-03 10:49 UTC, EdieLemoine commented on src/Plugin/Action/Order/PrintOrderAction.php
> +class PrintOrderAction extends AbstractOrderAction
Ik mis een call naar deze actie in de `EXPORT_AND_PRINT_ORDER` actie

2022-11-03 10:49 UTC, EdieLemoine commented on tests/Unit/Plugin/Action/Order/ExportOrderActionTest.php
> +it('prints order', function () {
enter ervoor

2022-11-08 09:34 UTC, wthijmen approved these changes

2022-11-08 13:52 UTC, EdieLemoine approved these changes

2022-11-08 15:28 UTC, merged