fix: cast orderId parameter to array
myparcelnl/pdk pull request #47
Opened 2022-11-09 10:31 UTC by Mark-Ernst

2022-11-09 11:16 UTC, wthijmen submitted a review, later dismissed

2022-11-10 08:26 UTC, joerivanveen approved these changes

2022-11-10 08:30 UTC, EdieLemoine requested changes

2022-11-10 08:30 UTC, EdieLemoine commented on src/Plugin/Action/Order/ExportOrderAction.php
> +        $orders = $this->orderRepository->getMany((array) $parameters['orderIds']);
Dit werkt niet als er meerdere orderIds in zitten, los het dan meteen goed op door netjes het format `id;id;id` te splitten. Misschien is het zelfs nice als `getMany` dat zelf doet

2022-11-10 14:41 UTC, EdieLemoine requested changes

2022-11-10 14:41 UTC, EdieLemoine commented on src/Plugin/Repository/AbstractPdkOrderRepository.php
> -     * @param  array $array
wel graag aangeven wat het moet zijn:

```
     * @param  string|string[] $array - Single id, array of ids or string of semicolon-separated ids.
```

2022-11-10 14:41 UTC, EdieLemoine commented on src/Plugin/Repository/AbstractPdkOrderRepository.php
> +        $array = array_reduce((array) $orderIds, static function (array $acc, string $item) {
Dit kan ook `Utils::toArray()` worden :)

2022-11-10 14:55 UTC, wthijmen submitted a review, later dismissed

2022-11-10 15:40 UTC, wthijmen approved these changes

2022-11-11 08:41 UTC, EdieLemoine approved these changes

2022-11-11 09:10 UTC, merged