fix(export): prevent export of irrelevant shipments
myparcelnl/pdk pull request #51
Opened 2022-11-15 14:23 UTC by Mark-Ernst

2022-11-15 15:59 UTC, wthijmen submitted a review, later dismissed

2022-11-18 07:36 UTC, wthijmen approved these changes

2022-11-18 09:07 UTC, joerivanveen requested changes
Zoals besproken, dit werkt niet met meerdere labels.

2022-11-25 08:45 UTC, joerivanveen approved these changes

2022-11-25 08:53 UTC, wthijmen submitted a review, later dismissed

2022-12-07 14:28 UTC, EdieLemoine commented
/test

2022-12-08 13:42 UTC, EdieLemoine requested changes

2022-12-08 13:42 UTC, EdieLemoine commented on src/Plugin/Action/Order/ExportOrderAction.php
> +        $shipments = $orders->generateShipments()
ik ben het hier niet echt mee eens, dit is de enige plek waar generateShipments gebruikt wordt, en ik zou dan ook eigenlijk verwachten dat die alleen de nieuwe shipments teruggeeft

2022-12-19 16:39 UTC, joerivanveen approved these changes

2022-12-23 10:18 UTC, closed without merging