fix(shipment): prevent cast error by adding carrier to delivery options
myparcelnl/pdk pull request #52
Opened 2022-11-16 12:35 UTC by Mark-Ernst

2022-11-16 16:08 UTC, wthijmen approved these changes

2022-11-18 07:36 UTC, wthijmen submitted a review, later dismissed

2022-11-21 08:06 UTC, wthijmen approved these changes

2022-11-25 08:44 UTC, joerivanveen approved these changes

2022-12-08 10:06 UTC, wthijmen approved these changes

2022-12-08 10:07 UTC, joerivanveen approved these changes

2022-12-08 10:08 UTC, EdieLemoine requested changes

2022-12-08 10:08 UTC, EdieLemoine commented on src/Shipment/Concern/HasDecodesShipment.php
> +            'updated'                  => $data['updated'] ?? null,
dit veld bestaat nooit

2022-12-08 12:12 UTC, closed without merging