fix(options): prevent returning null when packageType is already an id
myparcelnl/pdk pull request #54
Opened 2022-11-17 12:23 UTC by Mark-Ernst

2022-11-17 12:32 UTC, wthijmen approved these changes

2022-11-25 08:42 UTC, joerivanveen approved these changes

2022-12-07 13:28 UTC, EdieLemoine requested changes

2022-12-07 13:28 UTC, EdieLemoine commented on tests/Unit/Shipment/Model/Options/DeliveryOptionsTest.php
> +it('always returns an int as id', function () {
dit klinkt alsof je `id as int` bedoelt

2022-12-07 13:28 UTC, EdieLemoine commented on tests/Unit/Shipment/Model/Options/DeliveryOptionsTest.php
> +    expect($faultyDeliveryOptions->getDeliveryTypeId())
wanneer je een rij expects moet chainen moet je nadenken of je beter meerdere tests kan maken en/of `with` kunt gebruiken. Hier zou ik zeggen, maak 2 tests:

```
it('returns package type id as int', ...)->with(...)
```

en


```
it('returns delivery type id as int', ...)->with(...)
```

met dan meerdere cases in je `with` array.

2022-12-08 14:22 UTC, joerivanveen approved these changes

2023-05-16 15:02 UTC, closed without merging