feat(actions): add multicollo to export
myparcelnl/pdk pull request #66
Opened 2022-12-09 10:24 UTC by Mark-Ernst

2022-12-12 10:15 UTC, EdieLemoine approved these changes

2022-12-12 10:15 UTC, EdieLemoine requested changes

2022-12-12 10:15 UTC, EdieLemoine commented on src/Plugin/Model/PdkOrder.php
>      public function createShipment(array $data = []): Shipment
createShipments

2022-12-15 08:44 UTC, joerivanveen requested changes

2022-12-15 08:44 UTC, joerivanveen commented on src/Plugin/Model/PdkOrder.php
> +    public function createShipments(array $data = []): Shipment
Dat createShipments (meervoud) 1 shipment teruggeeft zit mij niet lekker, het is niet transparant bij het aanroepen wat hij dan create en welke hij dan teruggeeft?

2022-12-15 08:44 UTC, joerivanveen commented on src/Plugin/Action/Order/ExportOrderAction.php
> +    private function getShipments(PdkOrderCollection $orderCollection): ShipmentCollection
Dit is een tamelijk specifieke manier van het ophalen van shipments, zou dat misschien uit de naam van de method moeten blijken?

2022-12-15 08:44 UTC, joerivanveen commented on src/Plugin/Action/Order/ExportOrderAction.php
> +                $acc->push($shipments->last());
Is er geen scenario waarbij meerdere non-multicollo shipments in 1 request gemaakt worden, zoals nu wel kan vanuit de plugins? Of wordt dat elders opgevangen?

2022-12-19 13:32 UTC, wthijmen approved these changes

2022-12-19 16:36 UTC, joerivanveen requested changes

2022-12-19 16:36 UTC, joerivanveen commented on src/Plugin/Model/PdkOrder.php
> +        return $validationSchema['properties']['canBeMultiCollo']['enum'][0];
Misschien is er iets intelligents te bedenken dat je validatie waardes uit de OrderValidator magisch kunt optuigen en dan benaderen op de pdkorder.

2022-12-22 09:19 UTC, joerivanveen requested changes

2022-12-22 09:19 UTC, joerivanveen commented on src/Validation/OrderPropertyValidator.php
> +            $array = $array[$key];
Geeft dit geen warning als de key niet exists?

2022-12-22 09:19 UTC, joerivanveen commented on src/Validation/OrderPropertyValidator.php
> +        $result = $this->walkArrayByKeys($schema, $keys);
Ik zou hier $args[0] in een variabele laden zodat duidelijk is wat dat is, en als die ontbreekt kan je ook gelijk ophouden met deze method, als je 2 keer een waarde uit een array moet halen, is het in alle gevallen die mij bekend zijn sneller (goedkoper voor php) en makkelijker om die (de eerste keer) in een locale variabele de laden.

2022-12-22 09:19 UTC, joerivanveen commented on src/Validation/OrderPropertyValidator.php
> +        if (array_key_exists('minimum', $result)) {
Is minimum en maximum niet mooier te combineren, als je nog harder nadenkt?

2022-12-22 09:19 UTC, joerivanveen commented on src/Validation/OrderPropertyValidator.php
> +        if (array_key_exists('enum', $result)) {
Zoals besproken, is het wellicht mogelijk om isset te gebruiken op veel plekken ipv array_key_exists?

2022-12-22 09:19 UTC, joerivanveen commented on config/schema/myparcel/order/postnl/nl_package.json
> +        "canBeMultiCollo": {
Mocht je deze pr aanpassen, dan toch liever canHaveMultiCollo of iets anders dat in de lijn van de rest van de terminologie is. De 'Be' is hier toch te uniek achteraf gezien voor mijn gevoel.

2023-01-11 15:10 UTC, EdieLemoine approved these changes

2023-01-12 11:23 UTC, joerivanveen approved these changes

2023-01-12 11:32 UTC, merged