fix(export): use factor calculating insurance
myparcelnl/pdk pull request #98
Opened 2023-05-16 12:24 UTC by joerivanveen

2023-05-16 14:58 UTC, EdieLemoine requested changes
Ik mis tests hiervoor, dat de coverage 100% blijft is nice, maar dit wordt dus nog niet getest met andere waarden dan `1.0`

2023-05-16 14:58 UTC, EdieLemoine commented on src/App/DeliveryOptions/Service/ShipmentOptionsService.php
> +        $insuranceFactor = Settings::get(CheckoutSettings::EXPORT_INSURANCE_PRICE_FACTOR, CheckoutSettings::ID) ?? 1;
Wat is `1`?

2023-05-31 07:26 UTC, EdieLemoine requested changes

2023-05-31 07:26 UTC, EdieLemoine commented on tests/Unit/Plugin/Service/ShipmentOptionsServiceTest.php
> +    [0, 5000, 31000, .5, 25000],
Wat gebeurt er met factor 0, -5, 1.1, 0.1, -0.9 etc?

2023-06-06 09:16 UTC, EdieLemoine commented on src/App/DeliveryOptions/Service/ShipmentOptionsService.php
> +        }, AbstractSettingsModel::TRISTATE_VALUE_DEFAULT);
ik ga dit reverten, lijkt ongerelateerd aan de pr

2023-06-06 09:46 UTC, EdieLemoine approved these changes

2023-06-06 09:53 UTC, Mark-Ernst approved these changes

2023-06-06 09:58 UTC, merged